version: '3.8'

services:
  api:
    container_name: agsistemas_api
    image: joaodicous/agsistema:latest
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://db:5432/agsistemas
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - db
  db:
    container_name: 'ag_sistemas_db'
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: agsistemas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin