CREATE TABLE PROJETO(
  ID BIGSERIAL NOT NULL UNIQUE,
  ID_EXTERNO UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  DESCRICAO VARCHAR(255),
  DATA_HORA_CRIACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  DATA_HORA_ATUALIZACAO TIMESTAMP WITHOUT TIME ZONE,
  DATA_HORA_FINALIZACAO TIMESTAMP WITHOUT TIME ZONE,
  STATUS VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE(
  ID BIGSERIAL NOT NULL UNIQUE,
  ID_EXTERNO UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  NOME VARCHAR(255) NOT NULL,
  PRIMARY KEY(NOME)
);

CREATE TABLE ATIVIDADE(
  ID BIGSERIAL NOT NULL UNIQUE,
  ID_EXTERNO UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  TITULO VARCHAR(255) NOT NULL,
  DESCRICAO VARCHAR(255),
  DATA_HORA_CRIACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  STATUS VARCHAR(255) NOT NULL,
  PROJETO_ID BIGINT,
  ATIVIDADE_ID BIGINT,
  PRIMARY KEY(ID),
  FOREIGN KEY(PROJETO_ID) REFERENCES PROJETO(ID),
  FOREIGN KEY(ATIVIDADE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE PROJETOS_PARTICIPANTES(
  ID BIGSERIAL NOT NULL UNIQUE,
  PROJETO_ID BIGINT NOT NULL,
  CLIENTE_ID BIGINT NOT NULL,
  PRIMARY KEY(ID)
)